### PR TITLE
fix schema statements

### PR DESCRIPTION
**Pull request by kushkella**
I'm trying to remove features that are not supported by RedShift and also fix SQL queries where necessary.

### CODE REVIEW

**Comment by lorgio** [comment]
:+1:

**Comment by lorgio** [comment]
@kushkella you missed a spot on removing array. I added a PR to your repo so hopefully that should also update here

**Comment by GriffinHeart** [comment]
@lorgio Having the same issue, hopefully this gets merged, pinging @aamine

**Comment by aamine** [comment]
I missed this pull request... Thanks a lot.

**Pull request merged**
